### ISSUE TITLE
Can't setup for the first time

### ISSUE THREAD

**Issue by nasersobhan** [simplewebrtc/simplewebrtc-talky-sample-app#9]
I am trying to test this sample but when I enter npm install it shows me below errors at the end 
I am on windows 10 pro, nodeJS v12.16.2
![image](https://user-images.githubusercontent.com/9820012/81177593-283e0c00-8fbc-11ea-989f-0de7194de677.png)

**Comment by nasersobhan** [comment]
there is in ubuntu; 

```
WARN engine webrtc-adapter@7.5.1: wanted: {"npm":">=3.10.0","node":">=6.0.0"} (c                                                                                                   loadDep:rtcpeerconnection / |##########---------------------------------------|
WARN engine rtcpeerconnection-shim@1.2.15: wanted: {"npm":">=3.10.0","node":">=6                                                                                                   npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprec                                                                                                   ated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#dep                                                                                                   recated
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not re                                                                                                   commended for usage due to the number of issues. Please, upgrade your dependenci                                                                                                   es to the actual version of core-js@3.
loadDep:fsevents -> heade - |##############-----------------------------------|
WARN engine fsevents@2.1.2: wanted: {"node":"^8.16.0 || ^10.6.0 || >=11.0.0"} (c                                                                                                   npm ERR! Linux 4.15.0-99-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-meta                                                                                                   data.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package                                                                                                   -metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.                                                                                                   js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-packag                                                                                                   e-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package                                                                                                   -metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fe                                                                                                   tch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at                                                                                                   :
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/node/simplewebrtc-talky-sample-app/npm-debug.log

```

**Comment by AlbertoLeon** [comment]
I tested in v12.13.1 and worked, be sure you do npm install on root folder...
